export const GOOGLE_LOAD_SEARCH_RESULTS_SUCCESS = 'GOOGLE_LOAD_SEARCH_RESULTS_SUCCESS';
export const GOOGLE_LOAD_SEARCH_RESULTS_FAILURE = 'GOOGLE_LOAD_SEARCH_RESULTS_FAILURE';
export const OTHER_LOAD_SEARCH_RESULTS_SUCCESS = 'OTHER_LOAD_SEARCH_RESULTS_SUCCESS';
export const OTHER_LOAD_SEARCH_RESULTS_FAILURE = 'OTHER_LOAD_SEARCH_RESULTS_FAILURE';